EWP: Track Class Reference
Track Class Reference
#include <track.h>
Public Slots
int receiveValues (int, int)
void edit ()
Signals
void nameChanged ()
void durationChanged ()
Public Member Functions
Track (QString name, int duration, QDeclarativeItem *parent=0)
Track (QDeclarativeItem *parent=0)
QString name () const
void setName (const QString &name)
int duration () const
void setDuration (const int &duration)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
Properties
QString name
int duration
Detailed Description
Definition at line 9 of file track.h.
Constructor & Destructor Documentation
Track::Track (QString name, int duration, QDeclarativeItem * parent = 0)
Definition at line 13 of file track.cpp.
References setDuration(), and setName().
    : QDeclarativeItem(parent)
{
    // need to disable this flag to draw inside a QDeclarativeItem
    setFlag(QGraphicsItem::ItemHasNoContents, false);
    setName(name);
    setDuration(duration);
}
Track::Track (QDeclarativeItem * parent = 0) [explicit]
Definition at line 5 of file track.cpp.
    : QDeclarativeItem(parent)
{
    resultList = new QList<Editor*>;
    // need to disable this flag to draw inside a QDeclarativeItem
    setFlag(QGraphicsItem::ItemHasNoContents, false);
}
Member Function Documentation
int Track::duration () const
void Track::durationChanged () [signal]
void Track::edit () [slot]
Definition at line 31 of file track.cpp.
References Editor::VideoSplit().
                {
    for(int i = 0; i < resultList->size(); ++i){
        Editor::VideoSplit(resultList->at(i));
    }
}
QString Track::name () const
void Track::nameChanged () [signal]
void Track::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
Definition at line 55 of file track.cpp.
{
    QPen pen(Qt::black, 2);
    painter->setBrush(QBrush(Qt::black, Qt::SolidPattern));
    painter->setPen(pen);
    painter->setRenderHints(QPainter::Antialiasing, true);
    painter->drawEllipse(5.0, 5.0, 5.0, 5.0);
    //painter->drawEllipse(5.0, 5.0, 10.0, 10.0);
}
int Track::receiveValues (int value, int value2) [slot]
Definition at line 22 of file track.cpp.
{
    if(resultList->empty() == true){
        resultList->append(new Editor("/home/cecilia/Vidéos/bunny.mp4", value, value2));
    }else{
        resultList->append(new Editor("/home/cecilia/Vidéos/ludovik.mp4", value, value2));
    }
    return value;
}
void Track::setDuration (const int & duration)
Definition at line 51 of file track.cpp.
References duration().
{
     m_duration = duration;
 }
void Track::setName (const QString & name)
Definition at line 46 of file track.cpp.
References name().
 {
     m_name = name;
 }
Property Documentation
int Track::duration [read, write]
Definition at line 13 of file track.h.
QString Track::name [read, write]
Definition at line 12 of file track.h.
The documentation for this class was generated from the following files:
track.h
track.cpp