EWP: Chutier Class Reference
Chutier Class Reference
#include <chutier.h>
Public Slots
void hide ()
Signals
void sig_show (bool)
Public Member Functions
void Add (QList< QString > list)
void Weight (QList< QString > list)
void Play (QListWidgetItem *button)
QListWidget * getMediaList ()
Chutier (QWidget *parent=0)
virtual ~Chutier ()
void paintEvent (QPaintEvent *event)
void enterEvent (QEvent *event)
void leaveEvent (QEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
Protected Member Functions
virtual void showEvent (QShowEvent *e)
virtual void hideEvent (QHideEvent *e)
Detailed Description
Definition at line 26 of file chutier.h.
Constructor & Destructor Documentation
Chutier::Chutier (QWidget * parent = 0)
Definition at line 3 of file chutier.cpp.
References hide().
                               :QWidget(parent)
{
   QFont font;
   font.setBold(true);
   font.setPointSize(16);
   QFont font2;
   font2.setBold(true);
   font2.setPointSize(11);
   titre = new QLabel("Chutier", this);
   titre->setFont(font);
   titre->setAlignment(Qt::AlignTop);
   splitter = new QSplitter(Qt::Vertical, this);
   mediaList = new QListWidget();
   weightList = new QListWidget();
   playList = new QListWidget();
   mediaList->addItem("Clip");
   mediaList->setFont(font2);
   weightList->addItem("Poids (MB)");
   weightList->setFont(font2);
   playList->addItem("Lecture");
   playList->setFont(font2);
   splitter->addWidget(titre);
   QWidget *listcontainer = new QWidget(this); //widget chutier
   CSplitter = new QSplitter(Qt::Horizontal, this);
   cLayout = new QHBoxLayout;
   CSplitter->addWidget(mediaList);
   CSplitter->addWidget(weightList);
   CSplitter->addWidget(playList);
   cLayout->addWidget(CSplitter);
   listcontainer->setLayout(cLayout);
   splitter->addWidget(listcontainer);
   splitter->resize(300,400);
   m_State = STATE_DEFAULT;
   icone = new QPixmap("resources/exit.png");
   exitIcon = new QIcon(*icone);
   m_Exit = new QAction(*exitIcon,"fermer",this);
   this->addAction(m_Exit);
   connect(m_Exit, SIGNAL(triggered()), this, SLOT(hide()));
   connect(mediaList, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(updateCurrentweightmediaListItem(/*mediaList,weightList*/)));
   connect(mediaList, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(updateCurrentweightplayListItem(/*mediaList,weightList*/)));
   connect(weightList, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(updateCurrentmediaweightListItem(/*weightList,mediaList*/)));
   connect(weightList, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(updateCurrentmediaplayListItem(/*playList,weightList*/)));
   connect(playList, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(updateCurrentplayweightListItem(/*playList,weightList*/)));
   connect(playList, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(updateCurrentplaymediaListItem(/*playList,weightList*/)));
}
Chutier::~Chutier () [virtual]
Definition at line 161 of file chutier.cpp.
{
}
Member Function Documentation
void Chutier::Add (QList< QString > list)
Definition at line 134 of file chutier.cpp.
{
    if(mediaList)
    {
       if(!list.isEmpty()){
            mediaList->addItem(list.last());
            if(playList)
            {
                QListWidgetItem *icone = new QListWidgetItem();
                icone->setIcon(QIcon("resources/play.png"));
                playList->addItem(icone);
            }
        }
    }
}
void Chutier::enterEvent (QEvent * event)
Definition at line 212 of file chutier.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 250 && point.x() < 300)
    {
        m_State = STATE_HOVERED;
        update(275,2,18,18);
    }
}
QListWidget * Chutier::getMediaList ()
Definition at line 65 of file chutier.cpp.
{
    return mediaList;
}
void Chutier::hide () [slot]
Definition at line 264 of file chutier.cpp.
{
    this->setVisible(false);
}
void Chutier::hideEvent (QHideEvent * e) [protected, virtual]
Definition at line 276 of file chutier.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(false);
}
void Chutier::leaveEvent (QEvent * event)
Definition at line 224 of file chutier.cpp.
{
    Q_UNUSED(event);
    m_State = STATE_DEFAULT;
    update(275,2,18,18);
}
void Chutier::mousePressEvent (QMouseEvent * event)
Definition at line 232 of file chutier.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 250 && point.x() < 300)
    {
        m_State = STATE_CLICKED;
        update(275,2,18,18);
    }
}
void Chutier::mouseReleaseEvent (QMouseEvent * event)
Definition at line 245 of file chutier.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 250 && point.x() < 300)
    {
        if(underMouse())
        {
             m_State = STATE_HOVERED;
        }
        else{
             m_State = STATE_DEFAULT;
        }
    }
    m_Exit->trigger(); //on force le signal trigger de m_Exit
    update(275,2,18,18);
}
void Chutier::paintEvent (QPaintEvent * event)
Definition at line 167 of file chutier.cpp.
{
    Q_UNUSED(event);
    QPainter painter(this);
    switch(m_State)
    {
        case STATE_DEFAULT:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit.png"));
            break;
        case STATE_HOVERED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_hovered.png"));
            break;
        case STATE_CLICKED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_clicked.png"));
            break;
    }
    QLinearGradient gradient(0,0,0,15);
    gradient.setColorAt(0.0,QColor("#d9d9d9"));
    gradient.setColorAt(0.5,QColor("#c1c1c1"));
    QBrush brush(gradient);
    painter.setBrush(brush);
    painter.setPen(Qt::NoPen);
    static const int points[] = {5,0,(5/2),(5/2),0,5,0,15,300,15,300,5,(295+(5/2)),(5/2),295,0};
    QPolygon polygon;
    polygon.setPoints(8,points);
    painter.drawPolygon(polygon, Qt::OddEvenFill);
    //dessin des actions
    for(int i=0; i<this->actions().size(); ++i)
    {
        QAction *action = this->actions().at(i);
        painter.drawPixmap(280,2,action->icon().pixmap(12,12));
    }
}
void Chutier::Play (QListWidgetItem * button)
Definition at line 149 of file chutier.cpp.
{
            playList->addItem(button);
}
void Chutier::showEvent (QShowEvent * e) [protected, virtual]
Definition at line 270 of file chutier.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(true);
}
void Chutier::sig_show (bool) [signal]
void Chutier::Weight (QList< QString > list)
Definition at line 153 of file chutier.cpp.
{
    if(weightList)
    {
        if(!list.isEmpty())
            weightList->addItem(list.last());
    }
}
The documentation for this class was generated from the following files:
chutier.h
chutier.cpp