EWP: Pinceau Class Reference
Pinceau Class Reference
#include <pinceau.h>
Public Slots
void hide ()
Signals
void sig_show (bool)
Public Member Functions
Pinceau (QWidget *parent=0)
virtual ~Pinceau ()
void paintEvent (QPaintEvent *event)
void enterEvent (QEvent *event)
void leaveEvent (QEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
Protected Member Functions
virtual void showEvent (QShowEvent *e)
virtual void hideEvent (QHideEvent *e)
Detailed Description
Definition at line 13 of file pinceau.h.
Constructor & Destructor Documentation
Pinceau::Pinceau (QWidget * parent = 0)
Definition at line 3 of file pinceau.cpp.
References hide().
                               :QWidget(parent)
{
    QFont font;
    font.setBold(true);
    font.setPointSize(16);
    PLabel = new QLabel("Pinceau", this);
    PLabel->setFont(font);
    PLabel->setAlignment(Qt::AlignTop);
    //a enlever par la suite
    PLabel->resize(300,200);
    m_State = STATE_DEFAULT;
    icone = new QPixmap("resources/exit.png");
    exitIcon = new QIcon(*icone);
    m_Exit = new QAction(*exitIcon,"fermer",this);
    this->addAction(m_Exit);
    connect(m_Exit, SIGNAL(triggered()), this, SLOT(hide()));
}
Pinceau::~Pinceau () [virtual]
Definition at line 27 of file pinceau.cpp.
{
}
Member Function Documentation
void Pinceau::enterEvent (QEvent * event)
Definition at line 76 of file pinceau.cpp.
{
    Q_UNUSED(event);
    //position curseur à récupérer
    //http://qt.developpez.com/doc/4.7/qmouseevent/
    m_State = STATE_HOVERED;
    update(275,2,18,18); //on met à jour la zone de l'icone
}
void Pinceau::hide () [slot]
Definition at line 115 of file pinceau.cpp.
{
    this->setVisible(false);
}
void Pinceau::hideEvent (QHideEvent * e) [protected, virtual]
Definition at line 127 of file pinceau.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(false);
}
void Pinceau::leaveEvent (QEvent * event)
Definition at line 87 of file pinceau.cpp.
{
    Q_UNUSED(event);
    m_State = STATE_DEFAULT;
    update(275,2,18,18);
}
void Pinceau::mousePressEvent (QMouseEvent * event)
Definition at line 94 of file pinceau.cpp.
{
    Q_UNUSED(event);
    m_State = STATE_CLICKED;
    update(275,2,18,18);
}
void Pinceau::mouseReleaseEvent (QMouseEvent * event)
Definition at line 101 of file pinceau.cpp.
{
    Q_UNUSED(event);
    if(underMouse())
    {
         m_State = STATE_HOVERED;
    }
    else{
         m_State = STATE_DEFAULT;
    }
    m_Exit->trigger(); //on force le signal trigger de m_Exit
    update(275,2,18,18);
}
void Pinceau::paintEvent (QPaintEvent * event)
Definition at line 32 of file pinceau.cpp.
{
    Q_UNUSED(event);
    QPainter painter(this);
    switch(m_State)
    {
        case STATE_DEFAULT:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit.png"));
            break;
        case STATE_HOVERED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_hovered.png"));
            break;
        case STATE_CLICKED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_clicked.png"));
            break;
    }
    QLinearGradient gradient(0,0,0,15);
    gradient.setColorAt(0.0,QColor("#d9d9d9"));
    gradient.setColorAt(0.5,QColor("#c1c1c1"));
    QBrush brush(gradient);
    painter.setBrush(brush);
    painter.setPen(Qt::NoPen);
    static const int points[] = {5,0,(5/2),(5/2),0,5,0,15,300,15,300,5,(295+(5/2)),(5/2),295,0};
    QPolygon polygon;
    polygon.setPoints(8,points);
    painter.drawPolygon(polygon, Qt::OddEvenFill);
    //dessin des actions
    for(int i=0; i<this->actions().size(); ++i)
    {
        QAction *action = this->actions().at(i);
        painter.drawPixmap(280,2,action->icon().pixmap(12,12));
    }
}
void Pinceau::showEvent (QShowEvent * e) [protected, virtual]
Definition at line 121 of file pinceau.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(true);
}
void Pinceau::sig_show (bool) [signal]
The documentation for this class was generated from the following files:
pinceau.h
pinceau.cpp