EWP: Timeline Class Reference
Timeline Class Reference
#include <timeline.h>
Public Slots
void hide ()
Signals
void sig_show (bool)
Public Member Functions
Q_INVOKABLE void openMedia ()
Timeline (QWidget *parent=0)
virtual ~Timeline ()
void paintEvent (QPaintEvent *event)
void enterEvent (QEvent *event)
void leaveEvent (QEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
Protected Member Functions
virtual void showEvent (QShowEvent *e)
virtual void hideEvent (QHideEvent *e)
Detailed Description
Definition at line 17 of file timeline.h.
Constructor & Destructor Documentation
Timeline::Timeline (QWidget * parent = 0)
Definition at line 5 of file timeline.cpp.
References hide().
                                 :QWidget(parent)
{
    m_State = STATE_DEFAULT;
    icone = new QPixmap("resources/exit.png");
    exitIcon = new QIcon(*icone);
    m_Exit = new QAction(*exitIcon,"fermer",this);
    this->addAction(m_Exit);
    connect(m_Exit, SIGNAL(triggered()), this, SLOT(hide()));
}
Timeline::~Timeline () [virtual]
Definition at line 28 of file timeline.cpp.
{
}
Member Function Documentation
void Timeline::enterEvent (QEvent * event)
Definition at line 99 of file timeline.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 650 && point.x() < 700)
    {
        m_State = STATE_HOVERED;
        update(675,2,18,18);
    }
}
void Timeline::hide () [slot]
Definition at line 150 of file timeline.cpp.
{
    this->setVisible(false);
}
void Timeline::hideEvent (QHideEvent * e) [protected, virtual]
Definition at line 162 of file timeline.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(false);
}
void Timeline::leaveEvent (QEvent * event)
Definition at line 111 of file timeline.cpp.
{
    Q_UNUSED(event);
    m_State = STATE_DEFAULT;
    update(675,2,18,18);
}
void Timeline::mousePressEvent (QMouseEvent * event)
Definition at line 119 of file timeline.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 650 && point.x() < 700)
    {
        m_State = STATE_CLICKED;
        update(675,2,18,18);
    }
}
void Timeline::mouseReleaseEvent (QMouseEvent * event)
Definition at line 131 of file timeline.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 650 && point.x() < 700)
    {
        if(underMouse())
        {
             m_State = STATE_HOVERED;
        }
        else{
             m_State = STATE_DEFAULT;
        }
    }
    m_Exit->trigger(); //on force le signal trigger de m_Exit
    update(675,2,18,18);
}
void Timeline::openMedia ()
Definition at line 19 of file timeline.cpp.
{
    /*ui_openMediaList = new openMediaList();
    ui_openMediaList->setModal(true); //on empeche le clic sur le reste de la fenetre
    ui_openMediaList->exec();
    delete ui_openMediaList;
    ui_openMediaList = NULL;*/
}
void Timeline::paintEvent (QPaintEvent * event)
Definition at line 35 of file timeline.cpp.
{
    Q_UNUSED(event);
    QPainter painter(this);
    switch(m_State)
    {
        case STATE_DEFAULT:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit.png"));
            break;
        case STATE_HOVERED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_hovered.png"));
            break;
        case STATE_CLICKED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_clicked.png"));
            break;
    }
    QLinearGradient gradient(0,0,0,15);
    gradient.setColorAt(0.0,QColor("#d9d9d9"));
    gradient.setColorAt(0.5,QColor("#c1c1c1"));
    QBrush brush(gradient);
    painter.setBrush(brush);
    painter.setPen(Qt::NoPen);
    static const int points[] = {5,0,(5/2),(5/2),0,5,0,15,700,15,700,5,(695+(5/2)),(5/2),695,0};
    QPolygon polygon;
    polygon.setPoints(8,points);
    painter.drawPolygon(polygon, Qt::OddEvenFill);
    //dessin des actions
    for(int i=0; i<this->actions().size(); ++i)
    {
        QAction *action = this->actions().at(i);
        painter.drawPixmap(680,2,action->icon().pixmap(12,12));
    }
}
void Timeline::showEvent (QShowEvent * e) [protected, virtual]
Definition at line 156 of file timeline.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(true);
}
void Timeline::sig_show (bool) [signal]
The documentation for this class was generated from the following files:
timeline.h
timeline.cpp