EWP: Moniteur Class Reference
Moniteur Class Reference
#include <moniteur.h>
Public Slots
void hide ()
Signals
void sig_show (bool)
Public Member Functions
Moniteur (QWidget *parent=0)
virtual ~Moniteur ()
void paintEvent (QPaintEvent *event)
void enterEvent (QEvent *event)
void leaveEvent (QEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
VideoPlayer * getPlayer ()
Protected Member Functions
virtual void showEvent (QShowEvent *e)
virtual void hideEvent (QHideEvent *e)
Detailed Description
Definition at line 19 of file moniteur.h.
Constructor & Destructor Documentation
Moniteur::Moniteur (QWidget * parent = 0)
Definition at line 5 of file moniteur.cpp.
References hide().
                                 :QWidget(parent)
{
    QFont Mfont;
    Mfont.setBold(true);
    Mfont.setPointSize(16);
    m_player = new VideoPlayer(this);
    //player->resize(400, 250);
    QHBoxLayout *layout = new QHBoxLayout(this);
    layout->addWidget(m_player);
    m_player->resize(200,200);
    m_player->show();
    /*Setting CSS file*/
    /*QFile file("../player/playerStyleSheet.css");
    file.open(QFile::ReadOnly);
    QString playerStyleSheet = QLatin1String(file.readAll());
    player->setStyleSheet(playerStyleSheet);*/
    labMoniteur = new QLabel("Moniteur",this);
    labMoniteur->setFont(Mfont);
    labMoniteur->setAlignment(Qt::AlignTop);
    labMoniteur->setStyleSheet("padding-top : 2px;");
    m_State = STATE_DEFAULT;
    icone = new QPixmap("resources/exit.png");
    exitIcon = new QIcon(*icone);
    m_Exit = new QAction(*exitIcon,"fermer",this);
    this->addAction(m_Exit);
    connect(m_Exit, SIGNAL(triggered()), this, SLOT(hide()));
}
Moniteur::~Moniteur () [virtual]
Definition at line 44 of file moniteur.cpp.
{
}
Member Function Documentation
void Moniteur::enterEvent (QEvent * event)
Definition at line 94 of file moniteur.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 650 && point.x() < 700)
    {
        m_State = STATE_HOVERED;
        update(675,2,18,18);
    }
}
VideoPlayer* Moniteur::getPlayer () [inline]
Definition at line 33 of file moniteur.h.
{ return m_player; }
void Moniteur::hide () [slot]
Definition at line 139 of file moniteur.cpp.
{
    this->setVisible(false);
}
void Moniteur::hideEvent (QHideEvent * e) [protected, virtual]
Definition at line 151 of file moniteur.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(false);
}
void Moniteur::leaveEvent (QEvent * event)
Definition at line 106 of file moniteur.cpp.
{
    Q_UNUSED(event);
    m_State = STATE_DEFAULT;
    update(675,2,18,18);
}
void Moniteur::mousePressEvent (QMouseEvent * event)
Definition at line 113 of file moniteur.cpp.
{
    Q_UNUSED(event);
    QPoint point = this->mapFromGlobal(QCursor::pos());
    if(point.x() > 650 && point.x() < 700)
    {
        m_State = STATE_CLICKED;
        update(675,2,18,18);
    }
}
void Moniteur::mouseReleaseEvent (QMouseEvent * event)
Definition at line 125 of file moniteur.cpp.
{
    Q_UNUSED(event);
    if(underMouse())
    {
         m_State = STATE_HOVERED;
    }
    else{
         m_State = STATE_DEFAULT;
    }
    m_Exit->trigger(); //on force le signal trigger de m_Exit
    update(675,2,18,18);
}
void Moniteur::paintEvent (QPaintEvent * event)
Definition at line 49 of file moniteur.cpp.
{
    Q_UNUSED(event);
    QPainter painter(this);
    switch(m_State)
    {
        case STATE_DEFAULT:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit.png"));
            break;
        case STATE_HOVERED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_hovered.png"));
            break;
        case STATE_CLICKED:
            icone = NULL;
            m_Exit->setIcon(QIcon("resources/exit_clicked.png"));
            break;
    }
    QLinearGradient gradient(0,0,0,15);
    gradient.setColorAt(0.0,QColor("#d9d9d9"));
    gradient.setColorAt(0.5,QColor("#c1c1c1"));
    QBrush brush(gradient);
    painter.setBrush(brush);
    painter.setPen(Qt::NoPen);
    static const int points[] = {5,0,(5/2),(5/2),0,5,0,15,700,15,700,5,(695+(5/2)),(5/2),695,0};
    QPolygon polygon;
    polygon.setPoints(8,points);
    painter.drawPolygon(polygon, Qt::OddEvenFill);
    //dessin des actions
    for(int i=0; i<this->actions().size(); ++i)
    {
        QAction *action = this->actions().at(i);
        painter.drawPixmap(680,2,action->icon().pixmap(12,12));
    }
}
void Moniteur::showEvent (QShowEvent * e) [protected, virtual]
Definition at line 145 of file moniteur.cpp.
References sig_show().
{
    Q_UNUSED(e);
    emit sig_show(true);
}
void Moniteur::sig_show (bool) [signal]
The documentation for this class was generated from the following files:
moniteur.h
moniteur.cpp