EWP: VideoPlayer Class Reference
VideoPlayer Class Reference
#include <videoplayer.h>
Public Slots
void openFile ()
void play ()
void displayTime (int)
Public Member Functions
VideoPlayer (QWidget *parent=0)
void setNewMedia (const QString *filename)
~VideoPlayer ()
Detailed Description
Definition at line 18 of file videoplayer.h.
Constructor & Destructor Documentation
VideoPlayer::VideoPlayer (QWidget * parent = 0)
Definition at line 6 of file videoplayer.cpp.
References displayTime(), openFile(), and play().
    : QWidget(parent)
    , mediaPlayer(0, QMediaPlayer::VideoSurface)
    , playButton(0)
    , positionSlider(0)
    , label(0)
{
    QVideoWidget *videoWidget = new QVideoWidget;
    QAbstractButton *openButton = new QPushButton(tr("Open..."));
    connect(openButton, SIGNAL(clicked()), this, SLOT(openFile()));
    playButton = new QPushButton;
    playButton->setEnabled(false);
    playButton->setIcon(style()->standardIcon(QStyle::SP_MediaPlay));
    connect(playButton, SIGNAL(clicked()),
            this, SLOT(play()));
    positionSlider = new QSlider(Qt::Horizontal);
    positionSlider->setRange(0, 0);
    connect(positionSlider, SIGNAL(sliderMoved(int)),
            this, SLOT(setPosition(int)));
    label = new QLabel();
    displayTime(0);
    connect(positionSlider, SIGNAL(valueChanged(int)),
            this, SLOT(displayTime(int)));
    QBoxLayout *controlLayout = new QHBoxLayout;
    controlLayout->setMargin(0);
    controlLayout->addWidget(openButton);
    controlLayout->addWidget(playButton);
    controlLayout->addWidget(positionSlider);
    controlLayout->addWidget(label);
    QBoxLayout *layout = new QVBoxLayout;
    layout->addWidget(videoWidget);
    layout->addLayout(controlLayout);
    setLayout(layout);
    mediaPlayer.setVideoOutput(videoWidget);
    connect(&mediaPlayer, SIGNAL(stateChanged(QMediaPlayer::State)),
            this, SLOT(mediaStateChanged(QMediaPlayer::State)));
    connect(&mediaPlayer, SIGNAL(positionChanged(qint64)), this, SLOT(positionChanged(qint64)));
    connect(&mediaPlayer, SIGNAL(durationChanged(qint64)), this, SLOT(durationChanged(qint64)));
}
VideoPlayer::~VideoPlayer ()
Definition at line 57 of file videoplayer.cpp.
{
}
Member Function Documentation
void VideoPlayer::displayTime (int value) [slot]
This function create the time label placed under the slider and that display current time of the selected frame toward the total duration of the video ; the format changes as the video duration is superior to an hour or not between "mm:ss" and "hh:mm:ss".
Definition at line 61 of file videoplayer.cpp.
{
    QTime originTime(0,0,0);
    QTime hour(1,0,0);
    double mediaDuration = mediaPlayer.duration();
    QTime current_time = originTime.addSecs(qRound((double)value/1000));
    QTime duration = originTime.addSecs(qRound(mediaDuration/1000));
    /*Display time format according to the video duration : "mm:ss"  or  "hh:mm:ss" */
    if(duration < hour ){
        label->setText(current_time.toString("mm:ss")+" / "+duration.toString("mm:ss"));
    }else{
        label->setText(current_time.toString()+" / "+duration.toString());
    }
}
void VideoPlayer::openFile () [slot]
Definition at line 80 of file videoplayer.cpp.
{
    QString fileName = QFileDialog::getOpenFileName(this, tr("Open Movie"),QDir::homePath());
    if (!fileName.isEmpty()) {
        mediaPlayer.setMedia(QUrl::fromLocalFile(fileName));
        playButton->setEnabled(true);
    }
}
void VideoPlayer::play () [slot]
Definition at line 90 of file videoplayer.cpp.
{
    switch(mediaPlayer.state()) {
    case QMediaPlayer::PlayingState:
        mediaPlayer.pause();
        break;
    default:
        mediaPlayer.play();
        break;
    }
}
void VideoPlayer::setNewMedia (const QString * filename)
Definition at line 129 of file videoplayer.cpp.
{
    if (!filename->isEmpty()) {
        mediaPlayer.setMedia( QUrl::fromLocalFile((*filename)) );
        playButton->setEnabled(true);
    }
}
The documentation for this class was generated from the following files:
videoplayer.h
videoplayer.cpp